version: '3.8'

services:
  # Next.js Application
  app:
    build: .
    container_name: hrbooteh-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=hrbooteh_user
      - DB_PASSWORD=hrbooteh_secure_password_2024
      - DB_NAME=hrbooteh_db
      - JWT_SECRET=hrbooteh_jwt_secret_key_very_secure_2024
    depends_on:
      - mysql
    networks:
      - hrbooteh-network
    volumes:
      - ./logs:/app/logs

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: hrbooteh-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=hrbooteh_root_password_2024
      - MYSQL_DATABASE=hrbooteh_db
      - MYSQL_USER=hrbooteh_user
      - MYSQL_PASSWORD=hrbooteh_secure_password_2024
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_setup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hrbooteh-network
    command: --default-authentication-plugin=mysql_native_password

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: hrbooteh-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - hrbooteh-network

volumes:
  mysql_data:

networks:
  hrbooteh-network:
    driver: bridge
